worker:
  id: 2
  from: "a"
  to: "z"
  maxcnt: 5
  datagen: false
  handle_number: true

spring:
  rabbitmq:
    host: config.store.appzen.net
    port: 5672
    username: admin
    password: admin

