worker:
  id: 1
  from: "l"
  to: "z"
  maxcnt: 10
  datagen: false
  handle_number: true

spring:
  rabbitmq:
    host: config.store.appzen.net
    port: 5672
    username: admin
    password: admin
