worker:
  id: 0
  from: "a"
  to: "k"
  maxcnt: 20
  datagen: false
  handle_number: true

spring:
  rabbitmq:
    host: config.store.appzen.net
    port: 5672
    username: admin
    password: admin

